# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: main_air_test_app_innovation_lab_env

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ispttestcr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_09bc40aecaa04b70953729c69855d6f4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2a7d657884ae44cc9e8314ba6e9fdf97 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ispttestcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_09bc40aecaa04b70953729c69855d6f4 }}/sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:${{ github.sha }}
        file: ./WebApp.Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '923b2091-3e99-5e97-b292-6585565dae56'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4411fe91d7c741738ae8a78bd7bdc085 }}
        images: 'ispttestcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_09bc40aecaa04b70953729c69855d6f4 }}/sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:${{ github.sha }}'